# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CDK synth

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Amazon-kendra - Install dependencies & run synth
      run: |
        npm install -g aws-cdk@1.127.0
        cd amazon-kendra/cdk
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cdk synth
        echo "***Lint with pylint ****"
        pylint amazon-kendra/cdk/infra/

